version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "src/app/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
